[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pydisgro"
version = "0.1.0"
description = "python port of Disgro"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
pydisgro = ["data/*"]

[tool.setuptools.packages.find]
include = ["pydisgro*"]

[project.scripts]
pydisgro = "pydisgro.cli:main"
